version: '3.10'

services:

  mibackend:
    image: mibackend:0.0.1
    restart: always
    labels:
      traefik.enable: true
      # traefik.http.routers.mibackend.rule: "PathPrefix(`/`)"
      # traefik.http.routers.mibackend.entrypoints: "web"
      traefik.http.routers.mibackend.entrypoints: "websecure"
      traefik.http.routers.mibackend.rule: "Host(`minimateka.ru`)"
      # traefik.http.routers.mibackend.tls.certresolver: myresolver
      traefik.http.routers.mibackend.service: "mibackend"
      traefik.http.services.mibackend.loadbalancer.server.port: 8080

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345

#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongoexpress
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345

  proxy:
    image: traefik:v3.0
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock

  # whoami:
  #   image: traefik/whoami
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.whoami.rule=Host(`minimateka.ru`)"
  #     - "traefik.http.routers.whoami.entrypoints=websecure"
  #     - "traefik.http.routers.whoami.tls.certresolver=myresolver"
