version: '3.10'

services:

  mibackend:
    image: mibackend:0.0.1
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.mibackend.entrypoints: "websecure"
      traefik.http.routers.mibackend.rule: "Host(`minimateka.ru`)"
      traefik.http.routers.mibackend.tls.certresolver: "myresolver"
      traefik.http.routers.mibackend.service: "mibackend"
      # traefik.http.routers.mibackend.middlewares: "mibackend-https"
      # traefik.http.middlewares.mibackend-https.redirectscheme.scheme: "https"
      traefik.http.services.mibackend.loadbalancer.server.port: 8082

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345

#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongoexpress
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345

  proxy:
    image: traefik:v3.0
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
