api:
  debug: true
  dashboard: true
  insecure: true

log:
  level: DEBUG

accessLog: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

#certificatesResolvers:
#  #TODO:
#    acme:
#      email: #TODO
#      storage: #TODO
#      httpchallenge:
#        entryPoint: web